### ISSUE TITLE
Authorize doesn't work (at least not on homey FW v1.5.13)

### ISSUE THREAD

**Issue by MrZANE42** [denniedegroot/com.ring#21]
When trying to authorize as a ring user on homey with old web-based 1.5.13 firmware using the latest ring app (2.0.4) or the beta version (2.1.1) the authorization fails. 
Either nothing happens or an error message "Error: socket hang up" is shown.
The password isn't saved and it's not possible to add a ring device.
A few months ago I did add a ring doorbell under another account on this homey.
Things I've tried:
Uninstalling and reinstalling the app. 
Changing to beta app. 
Restarting the homey. 

Nothing seems to help.
Any advice?

Note! This isn't related to issue #16

**Comment by denniedegroot** [comment]
Can you send me a diagnostics report after you tried to authorize?

**Comment by MrZANE42** [comment]
Sure. Could you please tell me how to get the report?

**Comment by denniedegroot** [comment]
From within the Homey app. Go to settings -> apps -> Ring app -> Gear symbol -> send diagnostics report.

**Comment by MrZANE42** [comment]
Thanks for the tip but I can't find any gear symbol.
Keep in mind that I use the old firmware and the android platform.
When you say the app which version are you referring to the latest homey app (Which is only for 2.x fw.), the second latest or the Homey(Legacy)? I have them all installed but if I try to use the latest app. it requires me to first update my firmware which I rather not do just now (Need to verify that all my apps and stuff will work after the upgrade first). In the other apps. the only gear symbol I see is the one for settings which in the legacy app. gives you just a few options and in the version after that has some settings (including your ring app.) but no gear symbol.

I can download the app in dev. mode from my PC if that helps, maybe you output some useful data to console, or?

**Comment by denniedegroot** [comment]
That description is for the Homey 2.0 app. Running the app in dev mode from pc is fine too, just give me a complete dump of the output.

I have seen the updated reply but thats not much information to solve this.

**Comment by MrZANE42** [comment]
Hi. Here's a log from it running in dev. mode, hope it helps:
─────────────── Logging stdout & stderr ───────────────
com.ring running...
2019-06-01 00:35:00 [log] [ManagerDrivers] [chime] onInit
_verifyAuthentication
_authenticate
_https_auth
_refreshDevice
_https /dings/active
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketCloseListener (_http_client.js:363:23)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:561:12)
    at TCP.done [as _onclose] (_tls_wrap.js:360:7) code: 'ECONNRESET' }
_refreshDevice
_https /dings/active
_refreshDevice
_https /dings/active
_refreshDevice
_https /dings/active
_refreshDevice
_https /dings/active
_refreshDevice
_https /dings/active
_refreshDevice
_https /dings/active
_refreshDevice
_https /dings/active
_refreshDevice
_https /dings/active
_refreshDevice
_https /dings/active
_refreshDevice
_https /dings/active
_verifyAuthentication
_authenticate
_https_auth
_refreshDevice
_https /dings/active
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketCloseListener (_http_client.js:363:23)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:561:12)
    at TCP.done [as _onclose] (_tls_wrap.js:360:7) code: 'ECONNRESET' }
_refreshDevice
_https /dings/active
_refreshDevice
_https /dings/active
...

Maybe I should also say that I've had issues registering the doorbell here since I changed internet operator. I had to register it to my phone via mobile hotspot and then, after the device got registered, change the wifi credentials in the device to point to my normal wifi. This is the first, and only, thing I've found to not work on my network btw., very strange... And it might very well be related if it works for other people still using the old firmware.

**Comment by denniedegroot** [comment]
I don't see anything wrong, the "errors" happen sometimes when Ring closes the connection, but it's not related to the authentication. Are you sure you are entering the right username and password to authenticate? Or maybe your provider is blocking some url that Ring uses to authenticate?

The Homey firmware does not matter, it should also work for older firmware, nothing has changed for the newest firmware.

**Comment by denniedegroot** [comment]
No activity, closing issue.
